"""The module extension that fetches a prebuilt Verilator.

A consumer gets a repository, `@verilator_prebuilt`, holding the
binary this project released and the include tree Verilator reads at
run time, with a toolchain already declared over them.
"""

load(":versions.bzl", "DEFAULT_VERILATOR_VERSION", "VERILATOR_BINARIES")

_BUILD = '''\
# Generated by bazel_toolchains_verilator. Do not edit.
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
load("@rules_verilator//verilator:defs.bzl", "verilator_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "includes",
    srcs = glob(["include/**"]),
)

# Verilator reads its include tree at run time, so the tree travels
# with the binary as runfiles rather than being looked for on the
# machine that runs it.
native_binary(
    name = "verilator",
    src = "bin/verilator",
    out = "verilator",
    data = [":includes"],
)

verilator_toolchain(
    name = "toolchain_impl",
    verilator = ":verilator",
)

toolchain(
    name = "toolchain",
    toolchain = ":toolchain_impl",
    toolchain_type = "@rules_verilator//verilator:toolchain_type",
)
'''

def _prebuilt_impl(rctx):
    rctx.download_and_extract(url = rctx.attr.url, sha256 = rctx.attr.sha256)
    rctx.file("BUILD.bazel", _BUILD)

_prebuilt = repository_rule(
    implementation = _prebuilt_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "sha256": attr.string(mandatory = True),
    },
    doc = "A Verilator binary this project published, and its includes.",
)

_use = tag_class(attrs = {
    "version": attr.string(
        doc = "Which published Verilator to fetch.",
        default = DEFAULT_VERILATOR_VERSION,
    ),
})

# One platform is published today. A second becomes another key in
# `versions.bzl` and another leg of the release matrix; the lookup
# below is already written for it.
_PLATFORM = "linux_x86_64"

def _impl(module_ctx):
    version = DEFAULT_VERILATOR_VERSION
    for mod in module_ctx.modules:
        for use in mod.tags.use:
            version = use.version

    entry = VERILATOR_BINARIES.get(version)
    if entry == None:
        fail(
            "bazel_toolchains_verilator has no binary for Verilator {}. ".format(version) +
            "It has: {}.".format(", ".join(sorted(VERILATOR_BINARIES))),
        )
    binary = entry.get(_PLATFORM)
    if binary == None:
        fail(
            "bazel_toolchains_verilator has no {} binary for Verilator {}. ".format(_PLATFORM, version) +
            "It has: {}.".format(", ".join(sorted(entry))),
        )

    _prebuilt(
        name = "verilator_prebuilt",
        url = binary.url,
        sha256 = binary.sha256,
    )

verilator_binary = module_extension(
    implementation = _impl,
    tag_classes = {"use": _use},
    doc = "Fetches a Verilator binary this repository published.",
)
